### ISSUE TITLE
Cannot upload to Always Free ATP instance

### ISSUE THREAD

**Issue by jasonlyle88** [OraOpenSource/apex-nitro#326] opened 2020-01-17 15:20 UTC
### Issue Description
When I try to run `apex-nitro publish`, I get the below output. I have tested the connection with SQLcl stand alone, and that seems to be working okay.

```
apex-nitro publish nitrotest

    _     ____   _____ __  __    _   _  _  _
   / \   |  _ \ | ____|\ \/ /   | \ | |(_)| |_  _ __  ___
  / _ \  | |_) ||  _|   \  /    |  \| || || __|| '__|/ _ \
 / ___ \ |  __/ | |___  /  \    | |\  || || |_ | |  | (_) |
/_/   \_\|_|    |_____|/_/\_\   |_| \_||_| \__||_|   \___/

is compiling nitrotest ...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


...Done!
...Now publishing!
Uploading to 100 - Workspace Files...

SQLcl: Release 19.4 Production on Fri Jan 17 10:10:27 2020

Copyright (c) 1982, 2020, Oracle.  All rights reserved.

Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0

Uploaded: C:\Users\jason\Dropbox\Work\jmltest\plugins\nitrotest\build\js\igInlineRegion.js
java.sql.SQLException: ORA-06550: line 1, column 646:
PL/SQL: ORA-00904: "XDB"."DBMS_XDB"."CFG_GET": invalid identifier
ORA-06550: line 1, column 469:
PL/SQL: SQL Statement ignored
ORA-06550: line 1, column 1718:
PLS-00364: loop index variable 'I' use is invalid
ORA-06550: line 1, column 1703:
PL/SQL: Statement ignored

Uploaded: C:\Users\jason\Dropbox\Work\jmltest\plugins\nitrotest\build\js\igInlineRegion.js.map
java.sql.SQLException: ORA-06550: line 1, column 646:
PL/SQL: ORA-00904: "XDB"."DBMS_XDB"."CFG_GET": invalid identifier
ORA-06550: line 1, column 469:
PL/SQL: SQL Statement ignored
ORA-06550: line 1, column 1718:
PLS-00364: loop index variable 'I' use is invalid
ORA-06550: line 1, column 1703:
PL/SQL: Statement ignored

Uploaded: C:\Users\jason\Dropbox\Work\jmltest\plugins\nitrotest\build\js\igInlineRegion.min.js
java.sql.SQLException: ORA-06550: line 1, column 646:
PL/SQL: ORA-00904: "XDB"."DBMS_XDB"."CFG_GET": invalid identifier
ORA-06550: line 1, column 469:
PL/SQL: SQL Statement ignored
ORA-06550: line 1, column 1718:
PLS-00364: loop index variable 'I' use is invalid
ORA-06550: line 1, column 1703:
PL/SQL: Statement ignored


SQL>
Disconnected from Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0

Files were uploaded successfully.
```

### APEX Nitro Version
4.1.6

### Operating System
Windows 10

### Node Version
12.14.1

### Browser
N/A

### APEX Version
19.1

### Web Server
ORDS 19.3.0.r3191521, whatever server ATP uses for its setup (I'm not currently proxying through a compute node or anything, just basic ATP APEX instance)

### Project configuration screenshot
```json
{
  "mode": "advanced",
  "appURL": "https://ltcqzcb7pta7t0h-dbvna.adb.us-ashburn-1.oraclecloudapps.com/ords/f?p=100",
  "srcFolder": "C:\\Users\\jason\\Dropbox\\Work\\jmltest\\plugins\\nitrotest\\source",
  "distFolder": "C:\\Users\\jason\\Dropbox\\Work\\jmltest\\plugins\\nitrotest\\build",
  "js": {
    "processor": "default",
    "concat": false,
    "tsConcat": false
  },
  "css": {
    "language": "css",
    "concat": true,
    "concatFilename": "nitrotest.css"
  },
  "browsersync": {
    "realTime": true,
    "ghostMode": false,
    "notify": true
  },
  "header": {
    "enabled": false
  },
  "apex": {
    "openBuilder": false
  },
  "publish": {
    "destination": "workspace",
    "path": "sql",
    "connectionType": "custom",
    "connectionString": "vna_test/******@dbvna_high?TNS_ADMIN=C:\\\\oracle\\\\network\\\\admin\\\\wallets\\\\Wallet_DBVNA"
  }
}
```

**Comment by emoracle** [comment] 2020-01-30 14:19
I got it to work this way:
Go to the apex-publish-static-files module in node_modules.
In the lib directory you will find the distUpload. 

The problem is with the identification of the mime-type that will be passed to l_mime_type.

Jus remove the cursor that extracts the mimetype from the xdb configuration.

Next remove the for loop of the cursor. This will let the l_mimetype variable null, but the createFileAPI handles that with nvl's

**Comment by emoracle** [comment] 2020-01-30 20:03
if only they could make wwv_flow_mime_mapping_v or wwv_flow_api public by an apex_synonym and some grants....

**Comment by vincentmorneau** [comment] 2020-02-08 14:01
Thanks for posting your solution, I'll update apex-publish-static-files.

What do you mean by "the createFileAPI handles that with nvl's"?

**Comment by emoracle** [comment] 2020-02-08 14:22
In apex-pubish-static-files > lib > distUpload.js there is a variable createFileAPI. Within these PLSQL blocks l_mime_type is always handled with a default application/octet-stream.
This "generic binary data with unknown type" was good enough for my usecase.

**Comment by vincentmorneau** [comment] 2020-02-08 14:26
Ah. But JS or CSS files have to have a proper mimetype, don't they?

application/octet-stream will make them read as text.

What type of file are you uploading as application/octet-stream?

**Comment by vincentmorneau** [comment] 2020-08-18 18:30
Closing, as I never got a response since Feb 8.

**Closed by vincentmorneau** 2020-08-18 18:30 UTC
